

name: CI



on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    
    steps:
    
    - uses: actions/checkout@v2
    
    
  - name: Hugo setup
  uses: peaceiris/actions-hugo@v2.6.0
  with:
    extended: true
    
    
  - name: Build HUGO Site
     run: hugo
    
    
  - name: Deploy to GH Pages 
    uses: crazy-max/ghaction-github-pages@v3.1.0
    with: 
      target_branch: gh-pages
      build_dir: public
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
      
      
      
